/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fotoeditor;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FotoEditorTest {
    @Test void appHasAGreeting() {
        FotoEditor classUnderTest = new FotoEditor();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
