/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fotoeditor;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Dimension;

public class FotoEditor extends JFrame 
{
    public FotoEditor()
    {
        super();

        // Basic Features
        setTitle("FotoEditor v1 - Açık Kaynak Fotoğraf Düzenleme Programı");   
        setSize(getMaximumSize()); 

        // Menu
        JMenuBar FOTO_MENUBAR = new JMenuBar();
        {
            JMenu dosya   = new JMenu("Dosya");
            JMenu gorunum = new JMenu("Görünüm");
            JMenu ayarlar = new JMenu("Ayarlar");
            JMenu yardim = new JMenu("Yardım");
        
            FOTO_MENUBAR.add(dosya);
            FOTO_MENUBAR.add(gorunum);
            FOTO_MENUBAR.add(ayarlar);
            FOTO_MENUBAR.add(yardim);
        }   setJMenuBar(FOTO_MENUBAR);

        // Layouts
        BorderLayout BORDER_LAYOUT = new BorderLayout();
        setLayout(BORDER_LAYOUT);
        add(GuiObjects.DEFAULT_TOP_PANEL(), BORDER_LAYOUT.PAGE_START);
        
        
        setVisible(true);
    }

    public static void main(String[] args){
        new FotoEditor();
    }

}
